### PR TITLE
Arrow-Pattern-GC2002

### PR DESCRIPTION
**Pull request by GC2002**
I have done everything please merge and approve or label hacktoberfest-accepted
thanks!

### CODE REVIEW

**Comment by GC2002** [comment]
hi! what is the deal with this restyle bot? @aritraroy24

**Comment by aritraroy24** [comment]
@GC2002 don't worry....I'll sort and merge...actually this bot restyles your code for better looking...

**Comment by GC2002** [comment]
> @GC2002 don't worry....I'll sort and merge...actually this bot restyles your code for better looking...

ah thanks

**Comment by GC2002** [comment]
it shows:- Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by aritraroy24** [comment]
@GC2002 can u please check again?? actually, I added `hactoberfest` instead of `hacktoberfest`...spelling mistake...😖😖😖

**Comment by GC2002** [comment]
Yeah, it's good now. now it is just waiting for you to accept it

**Comment by aritraroy24** [comment]
@GC2002 btw you can add a line of asking for the input...it's a little bit confusing if one runs the program directly without looking at the code...I'll merge after ur checking of that `hacktoberfest ineligible` issue whether it's persisting or not...

**Comment by GC2002** [comment]
cool lemme do that

**Comment by aritraroy24** [comment]
@GC2002 😊😊😊

**Comment by aritraroy24** [comment]
@GC2002 Now, it's looking cooool...😊😊😊

**Comment by GC2002** [comment]
😄

**Pull request merged**
