### PR TITLE
added_pyramid_program

### PR DESCRIPTION
**Pull request by mk15012**
I have added a new pattern program. Thanks.

### CODE REVIEW

**Comment by mk15012** [comment]
I can't see the merge option.

**Review by mk15012 — COMMENTED** [review]
Kindly check. Everything is correct

**Review by aritraroy24 — COMMENTED** [review]
👏👏👏...I've merged that...

**Comment by mk15012** [comment]
> 👏👏👏...I've merged that...

So. I don't have to anything now right. Bcoz it is correct.

**Comment by aritraroy24** [comment]
I have just merged the restyle bot PR of your code...but I think for your original code all checks have not been passed...be sure...or I'll check tomorrow again...

**Pull request merged**
